name: dsci522-docker-env
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - libblas=3.11.0
  - libcblas=3.11.0
  - libexpat=2.7.3
  - libffi=3.5.2
  - libhwloc=2.12.1
  - libiconv=1.18
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libsqlite=3.51.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.6
  - mkl=2025.3.0
  - numpy=2.3.5
  - openssl=3.6.0
  - pandas=2.3.3
  - pip=25.3
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - setuptools=80.9.0
  - six=1.17.0
  - tbb=2022.3.0
  - tk=8.6.13
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - wheel=0.45.1
prefix: C:\Users\wuaitong\miniforge3\envs\dsci522-docker-env
